import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "How to find the right car part",
  description: "Find replacement car parts using the vehicle, engine, part location and manufacturer or OEM number.",
  alternates: { canonical: "/guides/finding-the-right-car-part" },
};

export default function FindingPartGuide() {
  return <main className="min-h-screen bg-[#07101e] px-4 py-10 text-white"><article className="mx-auto max-w-3xl"><Link href="/guides" className="text-sm font-semibold text-sky-300">← All guides</Link><p className="mt-12 text-xs font-bold uppercase tracking-[0.22em] text-emerald-300">Parts guide</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">How to find the right car part</h1><p className="mt-5 text-lg leading-8 text-slate-300">Cars that look identical can use different components. Start with evidence, not appearance alone.</p><div className="mt-10 space-y-7 text-slate-300"><section><h2 className="text-2xl font-bold text-white">1. Identify the vehicle precisely</h2><p className="mt-3 leading-7">Record the make, model, year, engine size, fuel type and body style. A production date or VIN may be needed when a model changed specification partway through a year.</p></section><section><h2 className="text-2xl font-bold text-white">2. Find the number on the old part</h2><p className="mt-3 leading-7">Clean the component carefully and look for an OEM, casting or manufacturer number. Search the complete number, including letters and suffixes. A one-character difference can describe a different revision.</p></section><section><h2 className="text-2xl font-bold text-white">3. Confirm location and measurements</h2><p className="mt-3 leading-7">Check front or rear, left or right, dimensions, connector shape and the number of mounting points. Photographs help recognition but do not prove fitment.</p></section><section><h2 className="text-2xl font-bold text-white">4. Ask the seller to confirm</h2><p className="mt-3 leading-7">Give the seller the vehicle details, VIN when appropriate, and the number from the existing part. Keep their compatibility confirmation with the order record.</p></section><section><h2 className="text-2xl font-bold text-white">5. Check the return terms</h2><p className="mt-3 leading-7">Confirm who pays return postage, whether opened or fitted parts can be returned, and whether electrical or special-order items are excluded.</p></section></div><aside className="mt-10 rounded-2xl border border-emerald-300/20 bg-emerald-300/[0.06] p-5 text-sm leading-6 text-emerald-100">Mekivo narrows marketplace searches; it does not guarantee compatibility. Verify the part number and fitment before purchasing.</aside><Link href="/" className="mt-8 inline-flex rounded-xl bg-emerald-300 px-5 py-3 font-bold text-emerald-950">Open the parts finder</Link></article></main>;
}
