import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  alternates: { canonical: "/privacy" },
  title: "Privacy",
  description: "How Mekivo handles search and vehicle information.",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-background px-4 py-12 text-foreground sm:px-6">
      <article className="mx-auto max-w-3xl rounded-3xl border border-outline/10 bg-panel/95 p-6 sm:p-10">
        <Link href="/" className="text-sm font-semibold text-link">← Back to Mekivo</Link>
        <h1 className="mt-7 text-4xl font-bold tracking-tight">Privacy</h1>
        <p className="mt-3 text-sm text-subtle">Last updated 9 October 2026</p>
        <div className="mt-8 space-y-7 text-sm leading-7 text-muted">
          <section><h2 className="text-lg font-bold text-foreground">Search information</h2><p className="mt-2">Searches are assembled in your browser. To show live eBay results, Mekivo sends the search terms to eBay through its server. When you choose a marketplace, relevant search terms are sent to that marketplace under its own privacy policy. Saved searches can be reopened through a Mekivo link containing search details; do not include sensitive personal information in free-text search fields.</p></section>
          <section><h2 className="text-lg font-bold text-foreground">Vehicle registrations</h2><p className="mt-2">When you use registration lookup, Mekivo sends the registration number to the Driver and Vehicle Licensing Agency (DVLA) Vehicle Enquiry Service and the Driver and Vehicle Standards Agency (DVSA) MOT History service to retrieve vehicle information such as make, model, year, engine size, fuel type, colour, MOT status and tax status. Mekivo uses this information to pre-fill the vehicle search you requested. The raw registration number is not stored in Mekivo&apos;s product-activity records. Standard hosting and security logs may record technical request information, but the lookup response is not publicly indexed or cached.</p></section>
          <section><h2 className="text-lg font-bold text-foreground">Accounts and saved data</h2><p className="mt-2">If you create an account, Mekivo stores your email address, authentication records, and the cars, parts or searches you choose to save. Saved listings keep a bookmark, the original seller link and your search details. Mekivo checks eBay for current listing details when you view them. If you choose Save before signing in, the selected listing is kept in this browser for up to 24 hours so you can finish saving it after sign-in. Authentication and database services are provided by Supabase. Security rules restrict saved records to the account that created them. You can remove individual saved items from your account.</p></section>
          <section><h2 className="text-lg font-bold text-foreground">Cookies and local storage</h2><p className="mt-2">Mekivo uses browser storage to keep an account signed in, remember your appearance preference and retain campaign attribution during your visit. It does not currently use advertising cookies or operate a payment system. Hosting providers may process standard technical logs needed to operate and secure the service.</p></section>
          <section><h2 className="text-lg font-bold text-foreground">Feedback and activity</h2><p className="mt-2">When signed in, suggestions or reports you submit and limited product activity such as searches and saved items may be recorded to operate support, understand usage and improve Mekivo. This information is restricted to your account and Mekivo&apos;s authorised owner account.</p></section>
          <section><h2 className="text-lg font-bold text-foreground">Website analytics</h2><p className="mt-2">Mekivo uses Vercel Web Analytics and Speed Insights to understand visits, performance and actions such as searches and marketplace clicks. We also record whether Mekivo opens in a browser or as a standalone home-screen app, and installation confirmations from browsers that provide them. These are aggregate usage figures, not a list of installed apps or identified users. Campaign labels in a link help us understand which posts and adverts brought visitors to the site. Custom analytics events do not include raw registration numbers, account email addresses or free-text searches. Signed-in account activity is recorded separately as described above.</p><p className="mt-2">Owner and testing browsers can be excluded from analytics. This stores only an exclusion setting in that browser, which remains after signing out. You can <Link href="/traffic-settings" className="font-semibold text-link">exclude this browser from visitor reports</Link>; clearing this site&apos;s browser data removes the setting.</p></section>
          <section><h2 className="text-lg font-bold text-foreground">Optional return-visit counting</h2><p className="mt-2">This separate counter is off until you choose to allow it. We remember only your choice and, with your permission, the time of your latest measured visit in this browser. There is no permanent visitor identifier, account link or browsing history in this counter. After at least 30 minutes without activity, returning to Mekivo can send a return-visit event to Vercel Web Analytics. The event has only a fixed browser label and the Mekivo homepage address; it does not include a timestamp from your browser, campaign label, registration, search terms or account information. Vercel processes the ordinary request information described in its <a href="https://vercel.com/docs/analytics/privacy-policy" className="font-semibold text-link" target="_blank" rel="noopener noreferrer">analytics privacy information</a>.</p><p className="mt-2">We use your consent to understand repeat use and improve Mekivo. The owner sees an aggregate number of return occasions, not names or a list of people. One person can return several times. A first measured visit only starts the browser history; returns before this feature cannot be reconstructed. A remembered time older than 30 days is ignored and replaced on the next allowed visit. Browser storage does not automatically erase it while Mekivo is closed; turning counting off removes it where storage is available. Changing browsers, devices or clearing storage can prevent a return being recognised.</p><p className="mt-2">You can decline or withdraw at any time in <Link href="/return-visit-settings" className="font-semibold text-link">Return visit settings</Link>. This stops future return counting and removes its stored visit time; previously aggregated figures are not individually identifiable and cannot be linked back to remove one visitor&apos;s events. Your choice is remembered in this browser until you change it or clear its storage. Searching, accounts and saved items work either way. This choice controls only the new return counter; existing website analytics and the owner/testing exclusion described above remain separate.</p></section>
          <section><h2 className="text-lg font-bold text-foreground">Why information is used</h2><p className="mt-2">Account information is used to provide the service you request. Support records, security logs and limited usage information are used to operate, protect and improve Mekivo. Mekivo does not sell personal information or use it for targeted advertising.</p></section>
          <section><h2 className="text-lg font-bold text-foreground">Retention</h2><p className="mt-2">Registration numbers entered for a lookup are not added to Mekivo&apos;s product-activity records. Account data is retained while your account remains active. Deleted accounts and their associated saved items, reports and activity are removed from the live database. Limited hosting and security logs may remain for their providers&apos; normal operational retention periods.</p></section>
          <section><h2 className="text-lg font-bold text-foreground">Your choices and rights</h2><p className="mt-2">The account page lets you download a copy of your data and, unless it is the protected service-owner account, permanently delete the account. You may also ask for access, correction, restriction or deletion through the <Link href="/support" className="font-semibold text-link">Mekivo support form</Link>.</p></section>
          <section><h2 className="text-lg font-bold text-foreground">Service providers and international processing</h2><p className="mt-2">Mekivo uses the DVLA Vehicle Enquiry Service and DVSA MOT History service for registration lookups, eBay for live listing searches, Wikimedia Commons for illustrative vehicle reference images, Vercel for hosting and website analytics, and Supabase for authentication and database services. Those providers may process relevant vehicle, technical or account information under their own data-processing and security terms.</p></section>
          <section><h2 className="text-lg font-bold text-foreground">Contact and operator</h2><p className="mt-2">Mekivo is operated by Adam Ayub. Privacy questions and complaints can be emailed to <a href="mailto:adamayub4@gmail.com" className="font-semibold text-link">adamayub4@gmail.com</a> or submitted through <Link href="/support" className="font-semibold text-link">Report a problem</Link>. Mekivo does not currently publish a business address because it has no public business premises.</p></section>
          <section><h2 className="text-lg font-bold text-foreground">External services</h2><p className="mt-2">Mekivo links to third-party marketplaces. Their terms and privacy notices apply after you leave Mekivo.</p></section>
        </div>
      </article>
    </main>
  );
}
