"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "../lib/supabase";

export default function ResetPasswordPage() {
  const [ready, setReady] = useState(false), [password, setPassword] = useState(""), [confirm, setConfirm] = useState(""), [message, setMessage] = useState("");
  useEffect(() => { const client = getSupabaseBrowserClient(); if (!client) return; client.auth.getSession().then(({ data }) => setReady(Boolean(data.session))); const { data } = client.auth.onAuthStateChange((event) => { if (event === "PASSWORD_RECOVERY" || event === "SIGNED_IN") setReady(true); }); return () => data.subscription.unsubscribe(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (password !== confirm) { setMessage("Passwords do not match."); return; } const { error } = await getSupabaseBrowserClient()!.auth.updateUser({ password }); setMessage(error ? error.message : "Password updated. You can now return to your account."); if (!error) { setPassword(""); setConfirm(""); } };
  return <main className="min-h-screen bg-[#07101e] px-4 py-10 text-white"><section className="mx-auto max-w-md rounded-3xl border border-white/10 bg-white/[0.035] p-7"><Link href="/account" className="text-sm text-sky-300">← Account</Link><h1 className="mt-6 text-3xl font-bold">Choose a new password</h1>{ready ? <form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm text-slate-300">New password<input required minLength={8} type="password" autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[0.06] px-4 py-3 text-white outline-none focus:border-sky-400/60" /></label><label className="block text-sm text-slate-300">Confirm password<input required minLength={8} type="password" autoComplete="new-password" value={confirm} onChange={(e) => setConfirm(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[0.06] px-4 py-3 text-white outline-none focus:border-sky-400/60" /></label>{message && <p role="status" className="text-sm text-sky-200">{message}</p>}<button className="w-full rounded-xl bg-sky-400 px-5 py-3 font-bold text-slate-950">Update password</button></form> : <p className="mt-5 text-slate-400">Open the recovery link from your email to continue.</p>}</section></main>;
}
