"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { getSupabaseBrowserClient, isSupabaseConfigured } from "../lib/supabase";

const fieldClass = "w-full rounded-xl border border-white/10 bg-white/[0.06] px-4 py-3 text-white outline-none placeholder:text-slate-500 focus:border-sky-400/60";
export default function SupportPage() {
  const [user, setUser] = useState<User | null>(null), [subject, setSubject] = useState(""), [message, setMessage] = useState(""), [status, setStatus] = useState(""), [loading, setLoading] = useState(isSupabaseConfigured());
  useEffect(() => { const client = getSupabaseBrowserClient(); if (!client) return; client.auth.getUser().then(({ data }) => { setUser(data.user); setLoading(false); }); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const client = getSupabaseBrowserClient(); if (!client || !user) return; setStatus("Sending…"); const { error } = await client.from("complaints").insert({ user_id: user.id, subject, message }); if (error) setStatus(error.message.includes("limit") ? "You have sent several reports recently. Please try again in an hour." : "We could not send this. Please try again."); else { setSubject(""); setMessage(""); setStatus("Your report has been sent to the CarScout owner."); } };
  return <main className="min-h-screen bg-[#07101e] px-4 py-8 text-white"><div className="mx-auto max-w-xl"><Link href="/" className="text-sm font-semibold text-sky-300">← Back to CarScout</Link><section className="mt-8 rounded-3xl border border-white/10 bg-white/[0.035] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-wider text-sky-300">Support</p><h1 className="mt-2 text-3xl font-bold">Report a problem or complaint</h1><p className="mt-3 text-sm leading-6 text-slate-400">Reports go to CarScout&apos;s private owner dashboard.</p>{!isSupabaseConfigured() ? <p className="mt-6 text-amber-300">Support accounts are being connected.</p> : loading ? <p className="mt-6 text-slate-400">Checking your account…</p> : !user ? <div className="mt-6 rounded-xl border border-white/10 p-4 text-sm text-slate-300">Please <Link href="/account" className="font-semibold text-sky-300">sign in or create an account</Link> before submitting a report.</div> : <form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm text-slate-300">Subject<input required minLength={3} maxLength={120} value={subject} onChange={(e) => setSubject(e.target.value)} className={`mt-2 ${fieldClass}`} /></label><label className="block text-sm text-slate-300">What happened?<textarea required minLength={10} maxLength={4000} rows={7} value={message} onChange={(e) => setMessage(e.target.value)} className={`mt-2 resize-y ${fieldClass}`} /></label>{status && <p role="status" className="text-sm text-sky-200">{status}</p>}<button className="rounded-xl bg-sky-400 px-5 py-3 font-bold text-slate-950">Send report</button></form>}</section></div></main>;
}
